// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domains/payment_services.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domains "github.com/neutrin/factory_methods/internal/domains"
)

// MockPaymentService is a mock of PaymentService interface.
type MockPaymentService struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentServiceMockRecorder
}

// MockPaymentServiceMockRecorder is the mock recorder for MockPaymentService.
type MockPaymentServiceMockRecorder struct {
	mock *MockPaymentService
}

// NewMockPaymentService creates a new mock instance.
func NewMockPaymentService(ctrl *gomock.Controller) *MockPaymentService {
	mock := &MockPaymentService{ctrl: ctrl}
	mock.recorder = &MockPaymentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentService) EXPECT() *MockPaymentServiceMockRecorder {
	return m.recorder
}

// MakePayment mocks base method.
func (m *MockPaymentService) MakePayment(paymentDet interface{}) (domains.PaymentResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakePayment", paymentDet)
	ret0, _ := ret[0].(domains.PaymentResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakePayment indicates an expected call of MakePayment.
func (mr *MockPaymentServiceMockRecorder) MakePayment(paymentDet interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakePayment", reflect.TypeOf((*MockPaymentService)(nil).MakePayment), paymentDet)
}
